AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: My serverless application
Resources:
  MyLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: my-lambda
      Handler: main
      Runtime: go1.x
      CodeUri: bin
      Description: 'My Lambda function'
      MemorySize: 128
      Timeout: 60